server:
  port: 8081


spring:
  application:
    name: kafka-zookeeper-producer

  kafka:
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094
    #bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
