server:
  port: 8083
  
spring:
  application:
    name: kafka-zookeeper-consumer

  kafka:
    # Use the cluster hostnames with the external, forwarded ports
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094
    consumer:
      group-id: explore-clean-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer